---

- name: Install basic components
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: install-packages

- name: Install VS Code
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: vscode

- name: Install docker
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: docker

- name: Install dbeaver
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: dbeaver

- name: Install clickhouse-client
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: clickhouse

- name: Install sublime-text
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: sublime-text

- name: Install virtual-box
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: virtual-box

- name: Install hashicorp terraform
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: hashicorp

- name: Install kubernetes kubectl
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: kubernetes

- name: Install helm
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - role: helm

- name: Install zsh
  hosts: localhost
  become true
  gather_facts: true
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: rmntrvn
          oh_my_zsh:
            install: yes
            theme: ys
            plugins:
              - git
              - gcloud
              - vagrant
              - terraform
              - kubectl
              - helm
              # - zsh-syntax-highlighting
              # - zsh-autosuggestions
              - vault
