---
- name: Add apt repository
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
    filename: '{{ item.filename }}'
  with_items: "{{ apt_repositories }}"
  register: result

- name: Add apt key
  apt_key: 
    url: "{{ item.key }}"
    state: present"
  with_items: "{{ apt_repositories }}"
  when: item.key is defined

- name: Update apt cache
  apt: update_cache=yes
  when: result|changed

