packages:
  - name: apt-transport-https
  - name: ca-certificates
  - name: cups
  - name: curl
  - name: dirmngr
  - name: dmidecode
  - name: filezilla
  - name: fping
  - name: gimp
  - name: git
  - name: gnupg
  - name: htop
  - name: inkscape
  - name: iperf3
  - name: jq
  - name: keepassxc
  - name: make
  - name: mc
  - name: neofetch
  - name: net-tools
  - name: nmap
  - name: obs-studio
  - name: openconnect
  - name: pavucontrol
  - name: peek
  - name: postgresql-client
  - name: pwgen
  - name: qbittorrent
  - name: remmina
  - name: resolvconf
  - name: s3cmd
  - name: shadowsocks-libev
  - name: simplescreenrecorder
  - name: sshpass
  - name: tcpdump
  - name: telnet
  - name: testdisk
  - name: thunderbird
  - name: vim
  - name: vlc
  - name: vokoscreen
  - name: wget
  - name: whois
  - name: wireguard
  - name: wireshark
  - deb: https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-x64.deb
  - deb: https://go.skype.com/skypeforlinux-64.deb
  - deb: https://discord.com/api/download?platform=linux&format=deb
  - deb: https://downloads.slack-edge.com/releases/linux/4.25.0/prod/x64/slack-desktop-4.25.0-amd64.deb
  - deb: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
  - deb: https://zoom.us/client/latest/zoom_amd64.deb
  - deb: https://dl.google.com/linux/deb/pool/main/g/google-chrome-stable/google-chrome-stable_100.0.4896.127-1_amd64.deb
  - deb: https://downloads.mongodb.com/compass/mongodb-compass_1.31.1_amd64.deb
  - deb: https://github.com/jgraph/drawio-desktop/releases/download/v17.4.2/drawio-amd64-17.4.2.deb